version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: geo_data
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/pg_data
    deploy:
      resources:
        limits:
          memory: '512M'
          cpus: '1'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
